Develop g1
CodingFactory-Repos/Coding-Tools pull request #195
Opened 2023-03-24 15:12 UTC by LeoJeanjean

Added/upgraded sprint and group creation forms

2023-03-24 15:21 UTC, Loule95450 requested changes
Please check your 15 bugs [Here](https://sonarcloud.io/project/issues?id=CodingFactory-Repos_Coding-Tools&pullRequest=195&resolved=false&types=BUG)

2023-04-29 17:45 UTC, Maghwyn approved these changes

2023-04-29 17:45 UTC, Maghwyn commented on front-end/src/api/scrum-req.ts
> +export const trySignup = (data: UserCreds) => {
Is this file used at all ?
Because it seems out of place.

2023-04-29 17:45 UTC, Maghwyn commented on front-end/src/components/NewGroup.vue
> +.popupcontainer {
We do use tailwind instead of manual css.
But for the sake of not losing time it's fine we won't change it.

2023-05-13 23:30 UTC, closed without merging