postits visibility to set by user write + user sylables on each postit
CodingFactory-Repos/Coding-Tools pull request #370
Opened 2023-06-04 17:37 UTC by Kevw94

2023-06-04 17:53 UTC, Maghwyn requested changes

2023-06-04 17:53 UTC, Maghwyn commented on back-end/src/base/retrospectives/retrospectives.controller.ts
> +	async newPostit(@Res() res: Response, @Body() body: Body, @Jwt() userId: ObjectId) {
Where is the dto ?

2023-06-04 17:53 UTC, Maghwyn commented on front-end/src/components/retrospective/Postit.vue
> +			:class="isPostitVisible || isOwner ? '' : 'wave-text'"
:class="{ 'wave-text': !isPostitVisible || !isOwner }"

2023-06-05 09:15 UTC, AyakorK approved these changes

2023-06-05 09:15 UTC, merged